version: '3.8'

services:
  robot-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stampcar-robot-tests
    volumes:
      # Mount logs directory to persist test results
      - ./Logs:/app/Logs
      # Mount robots directory for easy test file access
      - ./robots:/app/robots
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
    # Optional: expose port if web interface is needed
    ports:
      - "8080:8080"
    # Add shared memory size for Chrome stability
    shm_size: 2gb
    # Security options for Chrome in container
    security_opt:
      - seccomp:unconfined
    # Override default command if needed
    # command: ["python3", "run_robot.py", "--variable", "serial:4240"]
