version: '3.8'

services:
  robot-web-runner-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FLASK_ENV=development
      - DISPLAY=:99
    volumes:
      - .:/app
      - ./Logs:/app/Logs
    command: python main.py
    restart: unless-stopped
    networks:
      - robot-network

networks:
  robot-network:
    driver: bridge
